spring:
  datasource:
    main:
      jdbc-url: jdbc:mysql://172.20.72.78:3306/mou_truck_control?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
      username: root
      password: Ctfo@123

  # Redis配置
  redis:
    database: 0
    host: 172.20.72.78
    password:
    port: 6379


# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

